apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: starships.ships.codecentric.de
spec:
  group: ships.codecentric.de
  names:
    kind: Starship
    plural: starships
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
          type: object
        status:
          properties:
            capacity:
              type: string
            costs:
              type: string
            crew:
              type: string
            model:
              type: string
            name:
              type: string
            passengers:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
